version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
      args:
        - RAILS_ENV
        - SECRET_KEY_BASE
    volumes:
      - .:/lumastic
    ports:
      - "80:3000"
    environment:
      PORT: "3000"
      DB_HOST: "lumastic-prod-db.cweydkfsbgul.us-east-1.rds.amazonaws.com"
      DB_USER: "lumastic"
      DB_PASSWORD: "lumasticdb"
      DB_NAME: "production"
      RAILS_ENV: "production"
      SECRET_KEY_BASE: "88526a8c8b04f85a93e2fee77f1108941ac0183f428ff5f9ef3c14167884caa26343b6c067c46270e0d1e7a98a5d1d24bc351bf017b7a45430a1178d0eb7b724"