version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - .:/lumastic
    ports:
      - "80:3000"
    environment:
      PORT: "3000"
      DB_HOST: "lumastic-db.cweydkfsbgul.us-east-1.rds.amazonaws.com"
      DB_USER: "lumastic"
      DB_PASSWORD: "thisismylumasticpassword"
      DB_NAME: "lumastic-db"
      RAILS_ENV: "production"