default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  pool: 5

development:
  <<: *default
  database: lumastic_development

production:
  <<: *default
  database: lumastic_production

test:
  <<: *default
  database: lumastic_test


