default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  pool: 5

development:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  pool: 5
  database: lumastic_development

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  pool: 5
  port: 5432
  sslmode: 'verify-full'
  sslrootcert: 'config/amazon-rds-ca-cert.pem'
  database: lumastic_production

test:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  pool: 5
  database: lumastic_test


